title: NiwiaL-Blog
description: ""
author:
  name: "niwial"
  email: "someone@somewebsite.somedomain"
  url: "https://niwial.github.io"
  

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "NiwiaL"
year : "2021"
